Draft: Cucumber Expressions AST to Regex expansion
cucumber-rs/cucumber-expressions pull request #2
Opened 2021-11-10 05:05 UTC by ilslv

Moved from cucumber-rs/cucumber#154   
Part of cucumber-rs/cucumber#124

## Synopsis

This `PR` implements `Cucumber expressions` `AST` into `Regex` expansion. 

## Solution

This is done with `IntoRegexCharIter` trait to avoid unnecessary overhead. 

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-10 05:41 UTC, ilslv commented
`derive_more` crate is dependent on `syn = 1`. That why after running `cargo +nightly update -Z minimal-versions` `syn` gets downgraded to `1.0`, where there is no `Path::get_ident()` method.

2021-11-19 06:06 UTC, ilslv commented
## FCM

```
Cucumber Expressions AST to Regex expansion (#2)
```

2021-11-19 18:13 UTC, tyranron requested changes
@ilslv mostly OK, just bikeshedding is required.

2021-11-19 18:13 UTC, tyranron commented on src/expand/mod.rs
> +    pub fn regex_with_parameters<Input, Parameters>(
It's hard to grasp the whole idea here. Can we provide a meaningful example?

2021-11-19 18:13 UTC, tyranron commented on src/expand/mod.rs
> +    iter::Once<Result<char, UnknownParameterError<Input>>>,
Once we have TAIT we won't need this aliases anymore. It's worth mentioning with TODO comment for future.

2021-11-19 18:13 UTC, tyranron commented on src/expand/mod.rs
> +//! definitions.
We also need to mention somewhere [upstream production rules](https://github.com/cucumber/cucumber-expressions/blob/main/ARCHITECTURE.md#production-rules).

If we align with them 1-to-1, then they should be referred in transformation functions docs directly.

2021-11-19 18:13 UTC, tyranron commented on src/lib.rs
> +    ExpansionError as Error, IntoRegexCharIter, ParametersProvider,
I think we can omit re-exporting feature in root. They're quite specific to live in their on module.

2021-11-19 18:13 UTC, tyranron commented on src/expand/mod.rs
> +pub use with_parameters::{ParametersProvider, WithParameters};
Could it be?
```rust
pub mod parameters;

pub use parameters::{Provider as ParametersProvider, WithCustom as WithCustomParameters};
```

2021-11-22 10:26 UTC, tyranron approved these changes

2021-11-22 10:29 UTC, merged